# Generated by Django 5.0.4 on 2024-05-10 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Start', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rolegrade',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='rolegrade',
            name='role',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='RoleGrade',
        ),
    ]
