# Generated by Django 5.0.4 on 2024-05-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_StaffAdmin',
            field=models.BooleanField(default=False),
        ),
    ]
