# Generated by Django 5.0.4 on 2024-05-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0009_alter_student_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='image',
        ),
        migrations.RemoveField(
            model_name='student',
            name='image',
        ),
        migrations.AlterField(
            model_name='branchadmin',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/branch'),
        ),
    ]
