# Generated by Django 5.0.4 on 2024-05-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0010_remove_staff_image_remove_student_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/staff'),
        ),
    ]
