# Generated by Django 5.0.4 on 2024-05-10 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Branch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Branch.branch')),
                ('LKG', models.BooleanField(default=False)),
                ('UKG', models.BooleanField(default=False)),
                ('G1', models.BooleanField(default=False)),
                ('G2', models.BooleanField(default=False)),
                ('G3', models.BooleanField(default=False)),
                ('G4', models.BooleanField(default=False)),
                ('G5', models.BooleanField(default=False)),
                ('G6', models.BooleanField(default=False)),
                ('G7', models.BooleanField(default=False)),
                ('G8', models.BooleanField(default=False)),
                ('G9', models.BooleanField(default=False)),
                ('G10', models.BooleanField(default=False)),
                ('G11', models.BooleanField(default=False)),
                ('G12', models.BooleanField(default=False)),
            ],
        ),
    ]
