# Generated by Django 5.0.4 on 2024-05-11 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Branch', '0002_grades'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grades',
            name='branch',
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.DeleteModel(
            name='Grades',
        ),
    ]
