# Generated by Django 5.0.4 on 2024-05-11 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Branch', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='branch',
        ),
        migrations.DeleteModel(
            name='Grades',
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.DeleteModel(
            name='Subjects',
        ),
    ]
