# Generated by Django 5.0.4 on 2024-05-11 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Branch', '0006_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='fa1_marks',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='fa2_marks',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='fa3_marks',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='fa4_marks',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='sa1_marks',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='sa2_marks',
        ),
        migrations.CreateModel(
            name='TotalMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fa1_marks', models.CharField(max_length=10)),
                ('fa2_marks', models.CharField(max_length=10)),
                ('fa3_marks', models.CharField(max_length=10)),
                ('fa4_marks', models.CharField(max_length=10)),
                ('sa1_marks', models.CharField(max_length=10)),
                ('sa2_marks', models.CharField(max_length=10)),
                ('Subjects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Branch.subjects')),
            ],
        ),
    ]
