# Generated by Django 5.0.4 on 2024-05-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Branch', '0007_remove_subjects_branch_remove_subjects_fa1_marks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalmarks',
            name='fa1_marks',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='totalmarks',
            name='fa2_marks',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='totalmarks',
            name='fa3_marks',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='totalmarks',
            name='fa4_marks',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='totalmarks',
            name='sa1_marks',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='totalmarks',
            name='sa2_marks',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
