# Generated by Django 5.0.4 on 2024-05-11 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Branch', '0008_alter_totalmarks_fa1_marks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grades',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='grades',
        ),
        migrations.RemoveField(
            model_name='totalmarks',
            name='Subjects',
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.DeleteModel(
            name='Grades',
        ),
        migrations.DeleteModel(
            name='Subjects',
        ),
        migrations.DeleteModel(
            name='TotalMarks',
        ),
    ]
