# Generated by Django 5.0.4 on 2024-05-11 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Branch', '0009_remove_grades_branch_remove_subjects_grades_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=100)),
                ('branch_code', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=40)),
                ('pincode', models.CharField(max_length=10)),
                ('contact_number', models.CharField(max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=10)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Branch.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('grades', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Branch.grades')),
            ],
        ),
        migrations.CreateModel(
            name='TotalMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fa1_marks', models.CharField(blank=True, max_length=10, null=True)),
                ('fa2_marks', models.CharField(blank=True, max_length=10, null=True)),
                ('fa3_marks', models.CharField(blank=True, max_length=10, null=True)),
                ('fa4_marks', models.CharField(blank=True, max_length=10, null=True)),
                ('sa1_marks', models.CharField(blank=True, max_length=10, null=True)),
                ('sa2_marks', models.CharField(blank=True, max_length=10, null=True)),
                ('Subjects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Branch.subjects')),
            ],
        ),
    ]
