# Generated by Django 5.0.4 on 2024-05-11 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Branch', '0010_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='user',
        ),
    ]
